Backend/#98 crud operations for listing
gilhrpenner/COMP4350 pull request #136
Opened 2022-02-23 23:16 UTC by akashd50

- Updated the users schema to add a `user_id` field.
- Removed the listing photos table since it was reduntant
- Implemented Crud operations for listings
- Found an issue that the request with photos is a form-data request type and while we can make it such that it also contains the listing data in a separate field, it just feels weird and kinda hacky way to do it so separated the listing and listing photos endpoint.
- Refactored the photos endpoint such that they are separated now

2022-02-23 23:52 UTC, gilhrpenner requested changes

2022-02-23 23:52 UTC, gilhrpenner commented on backend/src/modules/listing/createListing/CreateListingController.ts
> +            req.params?.userId,
Anything that requires user authentication/id etc we can get directly from `req.user` this will be default and we don't need to send with any requests.

Currently we do not have userId on `req.user` but you can add that or I will add on my next PR.

2022-02-23 23:52 UTC, gilhrpenner commented on backend/src/modules/listing/createListing/CreateListingController.ts
> +            req.params?.userId,
hmmmn I just saw that it is coming from a param so maybe I can just add that on the frontend for the listings (since you've got all crud ready) but  everything else we should be getting from `req.user`

2022-02-23 23:52 UTC, gilhrpenner commented on backend/src/modules/listing/getListing/GetListingController.ts
> +        this.createListingService = createListingService;
I really don't understand what is going on here but I am pretty sure it is wrong

2022-02-23 23:53 UTC, gilhrpenner commented on backend/src/modules/listing/createListing/CreateListingController.ts
> +            req.params?.userId,
You can resolve this conversation after you read it :D

2022-02-24 00:08 UTC, akashd50 commented on backend/src/modules/listing/getListing/GetListingController.ts
> +        this.createListingService = createListingService;
lol.. yeah this is named incorrectly.. I'll rename that!

2022-02-24 00:22 UTC, akashd50 commented on backend/src/modules/listing/createListing/CreateListingController.ts
> +            req.params?.userId,
Yeah, I think it'll nice to do that, will clean some stuff up! Maybe we can circle back to it later on!

2022-02-24 01:30 UTC, BrettDowneyuofm commented on backend/yarn.lock
What was changed?

2022-02-24 01:32 UTC, gilhrpenner commented on backend/yarn.lock
Good catch, I've been meaning to ask that, I've noticed that my yarn.lock and Akash always changes for no reason...

2022-02-24 01:35 UTC, BrettDowneyuofm commented on backend/yarn.lock
Strange, I just cleared node modules and re-ran yarn on master and for me I didn't get any modifications, so I'm not too sure then

2022-02-24 03:29 UTC, akashd50 commented on backend/yarn.lock
Yeah, no idea either..

2022-02-24 03:43 UTC, BrettDowneyuofm approved these changes
Looks good 👍

2022-02-24 03:52 UTC, akashd50 commented on backend/src/modules/listing/getListing/GetListingController.ts
> +        this.createListingService = createListingService;
I've fixed this!

2022-02-24 04:01 UTC, gilhrpenner approved these changes

2022-02-24 04:02 UTC, gilhrpenner commented
I am good with this commit, just don't merge it before creating the documentation for S3 or else I might get blocked 🥲

2022-02-24 04:58 UTC, akashd50 commented
> I am good with this PR, just don't merge it before creating the documentation for S3 or else I might get blocked 🥲
Sounds good, I've added the instructions to the readme.

2022-02-24 05:01 UTC, merged