Backend/profile photo endpoint #129
gilhrpenner/COMP4350 pull request #139
Opened 2022-02-24 23:30 UTC by akashd50

- Added an endpoint for the profile-picture
- Added GET, PUT, and DELETE
- Refactored and renamed S3 helper functions

2022-02-25 01:53 UTC, gilhrpenner requested changes
There are a few changes that really need to happen, specially the `/account` not being authenticated.

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/account/profilePicture/deleteProfilePicture/DeleteProfilePictureController.ts
> +import { S3StorageService } from '../../../s3/S3StorageService';
Would it be possible to use @module here to prevent this `../../../` ?

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/account/profilePicture/deleteProfilePicture/DeleteProfilePictureController.ts
> +        const email = req.user?.email;
There is no need to check user, it will always have that property or else the user is not authenticated and therefore will be rejected before entering your controller/service

`req.user.email`

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/account/profilePicture/getProfilePicture/GetProfilePhotoController.ts
> +        const userId = req.params?.userId;
For this existing PR I don't think we need to change since there's a lot more to this, but future PRs instead of validate `req.params?.userId` we should be using Joi, this way we have a cleaner validation and also more precise.

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/account/profilePicture/putProfilePicture/PutProfilePictureController.ts
> +        const email = req.user?.email;
Same thing here, can remove the `?`

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/account/profilePicture/putProfilePicture/PutProfilePictureController.ts
> +        private getAccountDataService: GetAccountDataService,
One thing I may have forgot to mention is that the only dependency you should be using in your controller is the Service, this way if in the future we decide to move away from `express.js` to another framework  we don't have to deal with anything. That obviously isn't a concern for this project, but I guess what I meant is that it breaks the SOLID principles.

`Liskov Substitution Principle` and `Interface Segregation Principle`

It also can results in us losing a few marks since we don't have 100% consistency, but I am not too worried about that right now.

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +        if (existingProfilePictureUUID?.length) {
You must love to add those `?` 🤣 
Whe use ? to ensure that property exists/is defined, but would be a best practice to always use Joi to validate everything ONCE and then we're good.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

2022-02-25 01:53 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/index.ts
> -router.use('/account', ensureAuthenticated, accountRoutes);
we need all routes in account to be authenticated, this will break a lot of code if there is no authentication.
If you need any of your routes inside account not to be authenticated you need to move elsewhere.

2022-02-25 02:06 UTC, akashd50 commented on backend/src/shared/infra/http/routes/index.ts
> -router.use('/account', ensureAuthenticated, accountRoutes);
So I think I just removed it from here but did add it inside the account.router.ts, to them individually whereever it was needed.. but I guess if you think its weird, I can change it back..

2022-02-25 02:24 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/index.ts
> -router.use('/account', ensureAuthenticated, accountRoutes);
Yes, it is better so we don't have to repeat ourselves every time we create a new endpoint, plus there is no risk in us forgetting to protect a route and since this route only handle account information it is safe to assume that all calls will require authentication

2022-02-26 08:31 UTC, gilhrpenner requested changes

2022-02-26 08:31 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/index.ts
> -router.use('/account', ensureAuthenticated, accountRoutes);
We need `ensureAuthenticated` here so all /account routes will inherit the `ensureAuthenticated`

2022-02-26 08:31 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/account.routes.ts
> +accountRoutes.get('/', ensureAuthenticated, (req, res) => {
`ensureAuthenticated` should be removed from here and stays on all /accounts routes

2022-02-26 08:31 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/account.routes.ts
> +accountRoutes.get('/:userId/profile-picture', (req, res) => {
If you don't need `/:userId/profile-picture` to be authenticated then this needs to be removed from /accounts and go to a different route but by default `ensureAuthenticated` must be on all account routes

2022-02-26 08:38 UTC, akashd50 commented on backend/src/shared/infra/http/routes/account.routes.ts
> +accountRoutes.get('/:userId/profile-picture', (req, res) => {
oh dang it, I forgot to remove it from this file.. I'll do that

2022-02-26 08:39 UTC, akashd50 commented on backend/src/modules/account/profilePicture/deleteProfilePicture/DeleteProfilePhotoController.ts
> +        await this.s3StorageService.deleteProfilePhoto(
Yup, it'll delete the existing picture and upload the new one! since we only store one uuid for profile photo in the db.. unless in the future we wanna keep track of multiple pictures.. then this can change!

2022-02-26 08:43 UTC, akashd50 commented on backend/src/shared/infra/http/routes/account.routes.ts
> +accountRoutes.get('/:userId/profile-picture', (req, res) => {
Okay fixed all this!

2022-02-26 19:04 UTC, merged