Backend/Cleanup listing/photos endpoints and make them consistent
gilhrpenner/COMP4350 pull request #155
Opened 2022-02-27 06:44 UTC by akashd50

- Moved listing photos endpoints to the photos file to make it consistent with other photos  endpoints.
- Simplified some of our endpoints
- ![image](https://user-images.githubusercontent.com/29110919/155871610-378360f2-1528-44df-8491-1ad1de3cd389.png)

- Refactored the s3 storage service to match our structure of repository and services
- Updated and refactored endpoints in our swagger doc

2022-02-28 06:30 UTC, gilhrpenner approved these changes
That was a lot to process, for future PRs please don't make it so big, changes of merge conflict are huge this one :/

2022-02-28 06:33 UTC, gilhrpenner requested changes
Can you squash those before merging?
Also, not sure how complicated our merge conflicts will be so we might need to work together on this

2022-03-01 00:13 UTC, akashd50 commented
Okay so I believe I have resolved the conflicts here so it should be good, but lets see if the tests pass!

2022-03-01 01:29 UTC, gilhrpenner approved these changes

2022-03-01 01:43 UTC, merged