Refactored the listing photos and profile photos to be public
gilhrpenner/COMP4350 pull request #170
Opened 2022-03-05 03:51 UTC by akashd50

Refactored all the related tests
Changed the schema to store profile, banner photo and listing photo urls
Changes to the listing controllers:
Get listing also returns the listing photo urls
Delete listing also removes all the listing photos

2022-03-05 05:43 UTC, gilhrpenner commented
I think we're just missing to update the README.md with the changes on the bucket

2022-03-05 06:13 UTC, gilhrpenner requested changes
When uploading a profile picture the old one is not being removed from S3, not that it makes any difference for this project. It might be easier to just keep all profile pictures with the userId, wouldn't it?

2022-03-05 06:47 UTC, akashd50 commented
> 

So right now, it does remove the existing photo when we put a new profile photo, because I thought that they be essentially untracked since we only store one url at a time!

2022-03-05 06:51 UTC, akashd50 commented on frontend/src/components/AccountGeneralPanel.vue
> +        store.commit('account/updateProfilePicture', response.data.photoURL);
Hmm.. I don't think this is right, I think the correct would be `response.data.photos[0].photoUrl`. Its the genric object for get photos requests for both listings and profile photo.

2022-03-05 06:52 UTC, akashd50 commented on frontend/src/components/AccountGeneralPanel.vue
> +        store.commit('account/updateProfilePicture', response.data.photoURL);
I can make this change and test it!

2022-03-05 06:52 UTC, gilhrpenner commented on frontend/src/components/AccountGeneralPanel.vue
> +        store.commit('account/updateProfilePicture', response.data.photoURL);
I did this and it worked?

2022-03-05 06:53 UTC, gilhrpenner commented
> > 
> 
> 
> 
> So right now, it does remove the existing photo when we put a new profile photo, because I thought that they be essentially untracked since we only store one url at a time!

Can you test it locally? I tried your branch and I have multiple profile pictures there

2022-03-05 06:53 UTC, akashd50 commented
> > > 
> > 
> > 
> > So right now, it does remove the existing photo when we put a new profile photo, because I thought that they be essentially untracked since we only store one url at a time!
> 
> Can you test it locally? I tried your branch and I have multiple profile pictures there

For sure, I'm pretty sure it worked, but I'll check again!

2022-03-05 06:55 UTC, gilhrpenner commented
> > > > 
> 
> > > 
> 
> > > 
> 
> > > So right now, it does remove the existing photo when we put a new profile photo, because I thought that they be essentially untracked since we only store one url at a time!
> 
> > 
> 
> > Can you test it locally? I tried your branch and I have multiple profile pictures there
> 
> 
> 
> For sure, I'm pretty sure it worked, but I'll check again!
> 
> 

Alright, let me know how the goes. Heading to bed now

2022-03-05 07:33 UTC, akashd50 commented on frontend/src/components/AccountGeneralPanel.vue
> +        store.commit('account/updateProfilePicture', response.data.photoURL);
Oh wait yeah, I was looking at the wrong endpoint, I think this return is inconsistent from the others, I'll change the return type and update this as well!

2022-03-05 20:14 UTC, akashd50 commented
Okay so fixed up some last bit of changes, updated readme and tested the profile photo and it does seem to work as intended. Would you try again and let me know if you still have issues @gilhrpenner!

2022-03-06 02:48 UTC, gilhrpenner approved these changes

2022-03-06 03:04 UTC, merged