Initial backend setup for uploading images to s3
gilhrpenner/COMP4350 pull request #89
Opened 2022-02-19 03:21 UTC by akashd50

Still early stages, lot to do especially getting the images back and stuff but I wanted to get an early review just to make sure that I'm not going too far in the wrong direction and have to revert my code and stuff.

Add the path for /images/:userId/:listingId the post works fine, still need to work on the get

2022-02-19 03:45 UTC, gilhrpenner requested changes
Overall you're going in the right direction, I'd just suggest you to check the two example implementations I did for login/register to have an idea on how to set up the services and controller (I don't think I saw a controller here in your code)

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +                console.log('Error', err);
We show throw and error and catch/handle it in the service or something

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +                console.log('Success', data.CORSRules);
I guess this is unnecessary? 

If you kept it just to aid while working on that, ignore this :D

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +        const listingId = req.params?.['listingId'];
Use destructuring for this

const { userId, listingId } = req.params;

And also add a validation with `Joi`

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +        if (userId && listingId && file) {
if (!userId || !listingId || !file) throw new AppError

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/modules/s3/S3StorageService.ts
> +        if (userId && listingId) {
if (!userId || !listingId) throw new AppError

2022-02-19 03:45 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/index.ts
> +router.use('/images', imagesRoutes);
This route will need to be protected (user logged in) so add a // TODO: something so we can later on com back to that

2022-02-20 02:41 UTC, gilhrpenner commented
I resolved all of my previous conversations because you changed it all a lot, will start a new set of conversations :D

2022-02-20 05:27 UTC, gilhrpenner commented
Can you squash your commits again, please and thank you

2022-02-21 00:56 UTC, gilhrpenner requested changes

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/index.ts
> -import express from "express";
This file here is no longer being used, we can safely delete.
In fact I believe I removed it but the thing just refused to leave the project lmao

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +export class ListingController {
I feel like we should have a controller for each use case, get, post and put.
Single-responsibility principle

I am willing to make a compromise here but let's see what others think/say
@MarkRobitaille @BrettDowneyuofm

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +                req.params as {
We should have a type or interface instead of `as`

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +                req.params as {
Same as above, need type/interface

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +        return res.send(response);
When the response code is 200 you don't need to implicitly say res.status(200) and in case you want to add it to a single line to keep it clean you can do `return res.send(data).sendStatus(200);

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +            req.params as {
type/interface

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/ListingController.ts
> +        console.log(allImages);
remove console.log

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +        const invalidFormatFiles = cloneDeep(testFiles);
I feel like we don't need loadash if all we need is a deep clone, we can use `JSON.parse(JSON.stringify(obj));` or `Object.assign({}, obj);`

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.ts
> +            region: 'us-east-1',
We should use .env here just in case we need to change this in the future, if not a .env for sure a const on top of the file

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.ts
> +        const { error: invalidInput } = verifyListingRequestBody(params);
I would add `Validation` at the end of the function's name to keep consistency and clarity

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/shared/infra/http/routes/listing.routes.ts
> +    console.log('post listing', req.params);
console.logs, also can you add a // TODO: protect this route just so we don't forget it?

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +        fieldname: 'imageFile',
`fieldname` and `originalname` should be in camelCase

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +                Deleted: params.Delete.Objects.map((o) => ({ Key: o.Key })),
Would be good to give a type to `(o)` if possible

2022-02-21 00:56 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.ts
> +    verifyListingRequestBody,
this hasn't been defined or has been exported

2022-02-21 01:02 UTC, akashd50 commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +        fieldname: 'imageFile',
So this is just the existing class format for Multer file object, not something I made up!

2022-02-21 02:16 UTC, akashd50 commented on backend/src/index.ts
> -import express from "express";
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:16 UTC, akashd50 commented on backend/src/modules/listing/ListingController.ts
> +export class ListingController {
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022! For now I'll just go with what you mentioned!

2022-02-21 02:16 UTC, akashd50 commented on backend/src/modules/listing/ListingController.ts
> +                req.params as {
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:16 UTC, akashd50 commented on backend/src/modules/listing/ListingController.ts
> +                req.params as {
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:17 UTC, akashd50 commented on backend/src/modules/listing/ListingController.ts
> +        return res.send(response);
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:17 UTC, akashd50 commented on backend/src/modules/listing/s3/S3StorageService.ts
> +        const { error: invalidInput } = verifyListingRequestBody(params);
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:17 UTC, akashd50 commented on backend/src/shared/infra/http/routes/listing.routes.ts
> +    console.log('post listing', req.params);
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:17 UTC, akashd50 commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +                Deleted: params.Delete.Objects.map((o) => ({ Key: o.Key })),
Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:17 UTC, akashd50 commented on backend/src/modules/listing/s3/S3StorageService.ts
> +    verifyListingRequestBody,
Don't know how this didn't get caught or any app errors, but Updated in 24b1ff003d3802c268a23c13f32876bb3837c022!

2022-02-21 02:19 UTC, gilhrpenner commented on backend/src/modules/listing/s3/S3StorageService.spec.ts
> +        fieldname: 'imageFile',
Good to know, I wasn't aware of that. Shame on multer lmao

2022-02-21 02:23 UTC, gilhrpenner approved these changes
Great, all good now! :)
If you can just squash one more time (easy to find mistakes if we ever need to rollback) and also remove loadash from the dependencies.

Good work there

2022-02-21 03:06 UTC, akashd50 commented
So the codeQL fails for the req.file.path, with the message of 'using user provided path'. But I think its a false flag, since the path is generated by Multer on the backend and doesn't come from the user. What do you think? I want to verify before I mark it false positive?

2022-02-22 01:26 UTC, BrettDowneyuofm approved these changes

2022-02-22 01:27 UTC, merged